### ISSUE TITLE
Nightly builds ?

### ISSUE THREAD

**Issue by ymoisan** [flathub/org.qgis.qgis#95]
I use Flatpak for QGIS on Ubuntu 20.04 and I like it very much.  Upgrading from 3.14 to 3.16 was painless.  Thanx !

I was wondering how hard would it be to package up the nightly builds.  On the Flathub side, would that require a org.qgis.qgis-nightly structure ?  I am thinking on setting up a small virtual machine with build capability to track changes daily.  As mentioned [in the build instructions](https://github.com/qgis/QGIS/blob/master/INSTALL.md#31-building-qgis-with-qt-5x) the idea is to compile as little code as possible by "using binary packages for all dependencies - building only the core QGIS stuff from source".  Could Flatpak help ?

EDIT : I see everything is always built from the ground up.  Would it then simply be a matter of changing the [branch](https://github.com/flathub/org.qgis.qgis/blob/ebea658547262f16b7d94ffa792b424336e6a867/org.qgis.qgis.json#L33) to `master`?

**Comment by aleixpol** [comment]
We could have a branch that builds master and maybe get it to flathub-beta, I'm not sure if that would be welcome by flathub maintainers though, as it would be a considerable strain on the systems.

But yes, having a branch that builds master instead of whatever version is stable is a matter of changing the branch and you'd get to build it quite easily and quickly, since the dependencies won't be changing from a day to another.

**Comment by ymoisan** [comment]
Thanx @aleixpol.  I'll try locally for now.  I can understand if all projects start to build their nightlies with Flatpak that may be hard on flathub infrastructure.

**Comment by aleixpol** [comment]
Cool, if you have any questions don't hesitate to reach out.
If you see a lot of people need it, we can consider bringing up the issue.

Good luck!
