### ISSUE TITLE
flatpak of QGIS 3.16.3 does not render jpg-raster-files

### ISSUE THREAD

**Issue by kk-qgis** [flathub/org.qgis.qgis#96]
flatpak of QGIS 3.16.3 doesnot render jpg-raster-files

#####Error############
Invalid Layer: GDAL provider Cannot open GDAL dataset /home/cirrusklaus/01-aktuelle-Projekte/233-UVS-Passau/01-Datenein-ausgang/Geodaten-von/210125-Lubis/DOP20_utm32_828500_5389500_500.jpg: libjpeg: Wrong JPEG library version: library is 62, caller expects 80 Raster layer Provider is not valid (provider: gdal, URI: /home/cirrusklaus/01-aktuelle-Projekte/233-UVS-Passau/01-Datenein-ausgang/Geodaten-von/210125-Lubis/DOP20_utm32_828500_5389500_500.jpg
#####################

QGIS version | 3.16.3-Hannover | QGIS code revision | 94ac9f21
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.32.1 | Running against SQLite | 3.32.1
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | KDE Flatpak runtime
Active python plugins | QuickMultiAttributeEdit3; polystrip; AnotherDXF2Shape; Serval; qfieldsync; db_manager; processing

**Comment by aleixpol** [comment]
Is this a regression for you or it never worked?

**Comment by kk-qgis** [comment]
It never worked. I also test with official aerial jpg-images from the national survey of Bavaria

**Comment by holesond** [comment]
I confirm the same issue exists in QGIS 3.16.5 installed via flatpak. When trying to add a tif raster layer containing compressed jpeg tiles, QGIS crashes with:

ERROR 1: JPEGLib:Wrong JPEG library version: library is 62, caller expects 80
qgis: tmp_tif_jpeg.c:1018: JPEGSetupDecode: Assertion `sp->cinfo.comm.is_decompressor' failed.

(I believe the assertion is called in a version of https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_jpeg.c.)
GDAL is linked to libjpeg.so.62 instead of libjpeg.so.8, which I think causes the issue:

`ldd /var/lib/flatpak/app/org.qgis.qgis/x86_64/lts/active/files/lib/libgdal.so | grep jpeg`
libjpeg.so.62 => not found

When I create a symbolic link named libjpeg.so.62 with target libjpeg.so.8 (all in the /var/lib/flatpak/app/org.qgis.qgis/x86_64/lts/active/files/lib64 directory), I get the following ldd output:

`ldd /var/lib/flatpak/app/org.qgis.qgis/x86_64/lts/active/files/lib/libgdal.so | grep jpeg`
/var/lib/flatpak/app/org.qgis.qgis/x86_64/lts/active/files/lib/libgdal.so: /var/lib/flatpak/app/org.qgis.qgis/x86_64/lts/active/files/lib64/libjpeg.so.62: version LIBJPEG_6.2 not found (required by /var/lib/flatpak/app/org.qgis.qgis/x86_64/lts/active/files/lib/libgdal.so)
	libjpeg.so.62 => /var/lib/flatpak/app/org.qgis.qgis/x86_64/lts/active/files/lib64/libjpeg.so.62 (0x00007f83d82ca000)

Furthermore, I found two similar unresolved issues related to GDAL:
https://trac.osgeo.org/gdal/ticket/3949
https://stackoverflow.com/questions/41503731/jpeg-compression-in-gdal-translate-wrong-jpeg-library-version
